### PR TITLE
Remove reference to variable that doesn't exist

### LINKED ISSUE #48: Error when using GitStorage
# Problem

I'm seeing the following error when trying to use this gem:

```
/app/vendor/bundle/ruby/2.0.0/bundler/gems/scraped_page_archive-9d8a6347d122/lib/scraped_page_archive/git_storage.rb:32:in `save': undefined local variable or method `ret' for #<ScrapedPageArchive::GitStorage:0x007fa0f35c4450> (NameError)
 	from /app/vendor/bundle/ruby/2.0.0/bundler/gems/scraped_page_archive-9d8a6347d122/lib/scraped_page_archive.rb:37:in `record'
 	from /app/vendor/bundle/ruby/2.0.0/bundler/gems/scraped_page_archive-9d8a6347d122/lib/scraped_page_archive.rb:18:in `record'
 	from /app/vendor/bundle/ruby/2.0.0/bundler/gems/scraped_page_archive-9d8a6347d122/lib/scraped_page_archive/capybara.rb:57:in `command'
 	from /app/vendor/bundle/ruby/2.0.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:75:in `visible_text'
 	from /app/vendor/bundle/ruby/2.0.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/node.rb:17:in `command'
 	from /app/vendor/bundle/ruby/2.0.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/node.rb:50:in `visible_text'
 	from /app/vendor/bundle/ruby/2.0.0/gems/capybara-2.6.2/lib/capybara/node/element.rb:61:in `block in text'
 	from /app/vendor/bundle/ruby/2.0.0/gems/capybara-2.6.2/lib/capybara/node/base.rb:84:in `synchronize'
 	from /app/vendor/bundle/ruby/2.0.0/gems/capybara-2.6.2/lib/capybara/node/element.rb:57:in `text'
 	from scraper.rb:145:in `block in scrape_people'
 	from scraper.rb:144:in `scrape_people'
 	from scraper.rb:289:in `<main>'
```

That error was specifically from running https://github.com/everypolitician-scrapers/spain_congreso_es/tree/750cf4576626570b1b86156e866e65c0ffefc5f7.

# Proposed solution

It looks like there is a stray `ret` variable being referenced that doesn't exist, introduced in https://github.com/everypolitician/scraped_page_archive/pull/42. So the fix is to remove that variable (and possibly add a regression test!).

### PR DESCRIPTION
**Pull request by chrismytton**
GitStorage was trying to reference a `ret` variable which doesn't exist,
which meant that when there were no files to commit it would raise an
exception and stop the scraper.

Fixes #48 

# Note to reviewer

I did try adding a regression test for this, but the `GitStorage` class tries to clone a repo before doing any operations on it. Trying to work around that in tests turned out to be a bit of a rabbit hole.

I think this is OK, since the plan is to try and tease bits of this repository out into separate tools which each focus on one job, at which point we can re-think how the git storage tool will work and write some tests for it as appropriate.

### CODE REVIEW

**Comment by chrismytton** [comment]
@tmtmtmtm 👀
